-- Layer 7 sanitized business event feed and one-time dashboard WebSocket tickets.
create table if not exists public.business_events (
    id bigint generated by default as identity primary key,
    business_id uuid not null references public.businesses(id) on delete cascade,
    event_type text not null check (event_type in (
        'channel.inbound.processed','connection.created','connection.status_changed',
        'automation.created','automation.enabled_changed','automation.execution_recorded',
        'handoff.requested','handoff.assigned','handoff.taken_over','handoff.returned_to_automation'
    )),
    entity_type text not null,
    entity_id text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists idx_business_events_business_id_cursor
    on public.business_events(business_id, id);

create table if not exists public.dashboard_event_tickets (
    id uuid primary key default gen_random_uuid(),
    business_id uuid not null references public.businesses(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    ticket_hash text not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);
create index if not exists idx_dashboard_event_tickets_expiry
    on public.dashboard_event_tickets(expires_at) where used_at is null;

alter table public.business_events enable row level security;
alter table public.dashboard_event_tickets enable row level security;
revoke all on table public.business_events, public.dashboard_event_tickets from anon, authenticated;
grant select, insert on table public.business_events to service_role;
grant select, insert, update on table public.dashboard_event_tickets to service_role;
comment on table public.business_events is 'Sanitized, durable business event stream; payload excludes message bodies and credentials.';
comment on table public.dashboard_event_tickets is 'Short-lived, one-use hashed tickets used to authorize dashboard WebSocket connections.';
