create table if not exists public.ai_usage_events (
    id bigint generated by default as identity primary key,
    request_id uuid not null unique,
    business_id uuid not null references public.businesses(id) on delete cascade,
    operation text not null check (operation in ('intent', 'response', 'summary')),
    model text not null,
    request_status text not null check (request_status in ('completed', 'failed', 'unknown')),
    prompt_tokens integer,
    completion_tokens integer,
    total_tokens integer,
    created_at timestamptz not null default now(),
    constraint ai_usage_events_nonnegative_tokens check (
        (prompt_tokens is null or prompt_tokens >= 0)
        and (completion_tokens is null or completion_tokens >= 0)
        and (total_tokens is null or total_tokens >= 0)
    )
);

create index if not exists idx_ai_usage_events_business_created
    on public.ai_usage_events (business_id, created_at desc);

alter table public.ai_usage_events enable row level security;
revoke all on table public.ai_usage_events from anon, authenticated;
grant select, insert on table public.ai_usage_events to service_role;
grant usage, select on sequence public.ai_usage_events_id_seq to service_role;

comment on table public.ai_usage_events is
    'Metadata-only AI request usage ledger; stores provider token counts but never prompts or completions.';
