create table if not exists public.business_faqs (
    id uuid primary key default gen_random_uuid(),
    faq_group_id uuid not null,
    business_id uuid not null references public.businesses(id) on delete cascade,
    version integer not null check (version > 0),
    question text not null check (length(btrim(question)) between 1 and 500),
    question_key text not null check (length(btrim(question_key)) between 1 and 500),
    answer text not null check (length(btrim(answer)) between 1 and 3000),
    status text not null default 'draft' check (status in ('draft', 'approved', 'superseded', 'archived')),
    created_by uuid not null,
    approved_by uuid,
    approved_at timestamptz,
    created_at timestamptz not null default now(),
    constraint business_faqs_group_version_unique unique (faq_group_id, version),
    constraint business_faqs_approval_fields check (
        (status = 'approved' and approved_by is not null and approved_at is not null)
        or (status <> 'approved' and approved_by is null and approved_at is null)
    )
);

create unique index if not exists idx_business_faqs_approved_question
    on public.business_faqs (business_id, question_key)
    where status = 'approved';
create index if not exists idx_business_faqs_business_group_version
    on public.business_faqs (business_id, faq_group_id, version desc);

create table if not exists public.business_faq_events (
    id bigint generated by default as identity primary key,
    business_id uuid not null references public.businesses(id) on delete cascade,
    faq_id uuid not null references public.business_faqs(id) on delete cascade,
    actor_id uuid not null,
    event_type text not null check (event_type in ('drafted', 'revised', 'approved', 'archived')),
    created_at timestamptz not null default now()
);
create index if not exists idx_business_faq_events_business_created
    on public.business_faq_events (business_id, created_at desc, id desc);

alter table public.business_faqs enable row level security;
alter table public.business_faq_events enable row level security;
revoke all on table public.business_faqs, public.business_faq_events from anon, authenticated;
grant select, insert, update on table public.business_faqs to service_role;
grant select, insert on table public.business_faq_events to service_role;
grant usage, select on sequence public.business_faq_events_id_seq to service_role;

create or replace function public.create_business_faq_version(
    p_faq_id uuid,
    p_business_id uuid,
    p_actor_id uuid,
    p_question text,
    p_question_key text,
    p_answer text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_group_id uuid;
    v_version integer;
    v_faq public.business_faqs%rowtype;
    v_event_type text;
begin
    if auth.role() <> 'service_role' then
        raise exception 'service_role_required' using errcode = '42501';
    end if;
    if p_business_id is null or p_actor_id is null
       or p_question is null or length(btrim(p_question)) not between 1 and 500
       or p_question_key is null or length(btrim(p_question_key)) not between 1 and 500
       or p_answer is null or length(btrim(p_answer)) not between 1 and 3000 then
        raise exception 'invalid_business_faq' using errcode = '22023';
    end if;

    if p_faq_id is null then
        v_group_id := gen_random_uuid();
        v_version := 1;
        v_event_type := 'drafted';
    else
        select faq_group_id into v_group_id
        from public.business_faqs
        where id = p_faq_id and business_id = p_business_id
        for update;
        if not found then
            return jsonb_build_object('error', 'not_found');
        end if;
        perform pg_advisory_xact_lock(hashtextextended(v_group_id::text, 0));
        select coalesce(max(version), 0) + 1 into v_version
        from public.business_faqs
        where business_id = p_business_id and faq_group_id = v_group_id;
        v_event_type := 'revised';
    end if;

    insert into public.business_faqs (
        faq_group_id, business_id, version, question, question_key,
        answer, status, created_by
    ) values (
        v_group_id, p_business_id, v_version, btrim(p_question), btrim(p_question_key),
        btrim(p_answer), 'draft', p_actor_id
    ) returning * into v_faq;

    insert into public.business_faq_events (business_id, faq_id, actor_id, event_type)
    values (p_business_id, v_faq.id, p_actor_id, v_event_type);
    return to_jsonb(v_faq);
end;
$$;

create or replace function public.review_business_faq(
    p_faq_id uuid,
    p_business_id uuid,
    p_actor_id uuid,
    p_decision text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_faq public.business_faqs%rowtype;
    v_result public.business_faqs%rowtype;
begin
    if auth.role() <> 'service_role' then
        raise exception 'service_role_required' using errcode = '42501';
    end if;
    if p_actor_id is null or p_decision not in ('approve', 'archive') then
        raise exception 'invalid_business_faq_review' using errcode = '22023';
    end if;
    select * into v_faq
    from public.business_faqs
    where id = p_faq_id and business_id = p_business_id
    for update;
    if not found then
        return jsonb_build_object('error', 'not_found');
    end if;

    if p_decision = 'approve' then
        if v_faq.status not in ('draft', 'approved') then
            raise exception 'business_faq_version_not_approvable' using errcode = '22023';
        end if;
        update public.business_faqs
           set status = 'superseded', approved_by = null, approved_at = null
         where business_id = p_business_id
           and faq_group_id = v_faq.faq_group_id
           and status = 'approved'
           and id <> p_faq_id;
        update public.business_faqs
           set status = 'approved', approved_by = p_actor_id, approved_at = now()
         where id = p_faq_id
         returning * into v_result;
        insert into public.business_faq_events (business_id, faq_id, actor_id, event_type)
        values (p_business_id, p_faq_id, p_actor_id, 'approved');
    else
        if v_faq.status not in ('draft', 'approved') then
            raise exception 'business_faq_version_not_archivable' using errcode = '22023';
        end if;
        update public.business_faqs
           set status = 'archived', approved_by = null, approved_at = null
         where id = p_faq_id
         returning * into v_result;
        insert into public.business_faq_events (business_id, faq_id, actor_id, event_type)
        values (p_business_id, p_faq_id, p_actor_id, 'archived');
    end if;
    return to_jsonb(v_result);
end;
$$;

revoke all on function public.create_business_faq_version(uuid, uuid, uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.review_business_faq(uuid, uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.create_business_faq_version(uuid, uuid, uuid, text, text, text) to service_role;
grant execute on function public.review_business_faq(uuid, uuid, uuid, text) to service_role;

comment on table public.business_faqs is
    'Business-authored FAQ versions. Only the single approved exact-question version is eligible for automated answers.';
comment on table public.business_faq_events is
    'Append-only audit history for business FAQ draft, revision, approval, and archive transitions.';
